#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,dynamic,slots,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.protocol.TBase import TBase, TExceptionBase


class Iface(object):
  def getValue(self, key):
    """
    Parameters:
     - key
    """
    pass

  def setValue(self, key, value):
    """
    Parameters:
     - key
     - value
    """
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def getValue(self, key):
    """
    Parameters:
     - key
    """
    self.send_getValue(key)
    return self.recv_getValue()

  def send_getValue(self, key):
    self._oprot.writeMessageBegin('getValue', TMessageType.CALL, self._seqid)
    args = getValue_args()
    args.key = key
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_getValue(self):
    iprot = self._iprot
    (fname, mtype, rseqid) = iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(iprot)
      iprot.readMessageEnd()
      raise x
    result = getValue_result()
    result.read(iprot)
    iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    if result.notFound is not None:
      raise result.notFound
    raise TApplicationException(TApplicationException.MISSING_RESULT, "getValue failed: unknown result");

  def setValue(self, key, value):
    """
    Parameters:
     - key
     - value
    """
    self.send_setValue(key, value)
    self.recv_setValue()

  def send_setValue(self, key, value):
    self._oprot.writeMessageBegin('setValue', TMessageType.CALL, self._seqid)
    args = setValue_args()
    args.key = key
    args.value = value
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_setValue(self):
    iprot = self._iprot
    (fname, mtype, rseqid) = iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(iprot)
      iprot.readMessageEnd()
      raise x
    result = setValue_result()
    result.read(iprot)
    iprot.readMessageEnd()
    return


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["getValue"] = Processor.process_getValue
    self._processMap["setValue"] = Processor.process_setValue

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_getValue(self, seqid, iprot, oprot):
    args = getValue_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = getValue_result()
    try:
      result.success = self._handler.getValue(args.key)
    except NotFoundError, notFound:
      result.notFound = notFound
    oprot.writeMessageBegin("getValue", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_setValue(self, seqid, iprot, oprot):
    args = setValue_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = setValue_result()
    self._handler.setValue(args.key, args.value)
    oprot.writeMessageBegin("setValue", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class getValue_args(TBase):
  """
  Attributes:
   - key
  """

  __slots__ = [ 
    'key',
   ]

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'key', None, None, ), # 1
  )

  def __init__(self, key=None,):
    self.key = key

  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.key)
    return value


class getValue_result(TBase):
  """
  Attributes:
   - success
   - notFound
  """

  __slots__ = [ 
    'success',
    'notFound',
   ]

  thrift_spec = (
    (0, TType.STRING, 'success', None, None, ), # 0
    (1, TType.STRUCT, 'notFound', (NotFoundError, NotFoundError.thrift_spec), None, ), # 1
  )

  def __init__(self, success=None, notFound=None,):
    self.success = success
    self.notFound = notFound

  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.success)
    value = (value * 31) ^ hash(self.notFound)
    return value


class setValue_args(TBase):
  """
  Attributes:
   - key
   - value
  """

  __slots__ = [ 
    'key',
    'value',
   ]

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'key', None, None, ), # 1
    (2, TType.STRING, 'value', None, None, ), # 2
  )

  def __init__(self, key=None, value=None,):
    self.key = key
    self.value = value

  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.key)
    value = (value * 31) ^ hash(self.value)
    return value


class setValue_result(TBase):

  __slots__ = [ 
   ]

  thrift_spec = (
  )

  def __hash__(self):
    value = 17
    return value

