#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,slots,dynamic
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.protocol.TBase import TBase, TExceptionBase



class HealthStatus(TBase):
  """
  Attributes:
   - ok
   - message
  """

  __slots__ = [ 
    'ok',
    'message',
   ]

  thrift_spec = (
    None, # 0
    (1, TType.BOOL, 'ok', None, None, ), # 1
    (2, TType.STRING, 'message', None, None, ), # 2
  )

  def __init__(self, ok=None, message=None,):
    self.ok = ok
    self.message = message

  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.ok)
    value = (value * 31) ^ hash(self.message)
    return value

